apiVersion: v1 # loadbalances the pods on a static IP
kind: Service
metadata:
    name: {{ .Release.Name }}
    labels:
        app.kubernetes.io/name: support-api
        app.kubernetes.io/instance: {{ .Release.Name }}
spec: # instructions for the service
    type: {{ .Values.service.type }}
    ports:
        - name: http
          port: {{ .Values.service.port }}
          targetPort: http
          protocol: TCP
    selector:
        app.kubernetes.io/name: support-api
        app.kubernetes.io/instance: {{ .Release.Name }}